#if !defined(__6B1D5B82_A6BA_4CB0_A257_A3E2593880BD__)
#define __6B1D5B82_A6BA_4CB0_A257_A3E2593880BD__

#define FILE_VERSION_MAJOR  1
#define FILE_VERSION_MINOR 0
#define FILE_VERSION_PATCH 0
#define FILE_VERSION_BUILD 1

#define PRODUCT_VERSION_MAJOR FILE_VERSION_MAJOR
#define PRODUCT_VERSION_MINOR FILE_VERSION_MINOR
#define PRODUCT_VERSION_PATCH FILE_VERSION_PATCH
#define PRODUCT_VERSION_BUILD FILE_VERSION_BUILD

#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)

#define FILE_VERSION TOSTRING(\
FILE_VERSION_MAJOR) "." \
TOSTRING(FILE_VERSION_MINOR) "." \
TOSTRING(FILE_VERSION_PATCH) "." \
TOSTRING(FILE_VERSION_BUILD)

#define PRODUCT_VERSION TOSTRING(\
PRODUCT_VERSION_MAJOR) "." \
TOSTRING(PRODUCT_VERSION_MINOR) "." \
TOSTRING(PRODUCT_VERSION_PATCH) "." \
TOSTRING(PRODUCT_VERSION_BUILD)

#define COMPANYNAME "SKSTU®"
#define FILEDESCRIPTION "Communication Module"
#define INTERNALNAME "uvpp"
#define LEGALCOPYRIGHT "© SKSTU***Martell. All rights reserved."
#define ORIGINALFILENAME "uvpp.dll"
#define PRODUCTNAME "Public Project Module"

const unsigned long FILE_VERSION_HEX = \
((unsigned short)FILE_VERSION_MAJOR << (6 * 4)) | \
((unsigned short)FILE_VERSION_MINOR << (4 * 4)) | \
((unsigned short)FILE_VERSION_PATCH << (2 * 4)) | \
((unsigned short)FILE_VERSION_BUILD << (0 * 4));

#define PRODUCT_VERSION_HEX FILE_VERSION_HEX

/// /*_ Memade®（新生™） _**/
/// /*_ Tue, 03 Dec 2024 02:18:04 GMT _**/
/// /*_____ https://www.skstu.com/ _____ **/
#endif///__6B1D5B82_A6BA_4CB0_A257_A3E2593880BD__

